# main config file for pelmanism

engine:
    players: [ 'Tom', 'Mary', 'Alice', 'James', 'Natasha' ]

deck:
    cards: 
        'Hearts, Diamonds, Clubs, Spades': [ 'A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K' ]
        'Red, Black': [ 'Joker' ]

    generic_cards: [ 'Joker' ] 